name: Endor Labs Scan
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions: 
      security-events: write
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Setup JDK with Maven
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      
      - name: Build release package
        run: mvn -B clean install
        
        
      - name: Scan with Endor Labs
        uses: endorlabs/github-action@main
        with:
          namespace: github-endor-las
          api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          enable_github_action_token: false
          scan_summary_output_type: table
          ci_run: true
          sarif_file: endor-labs.sarif
      
      - name: Upload SARIF to github
        uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
        with:
          sarif_file: endor-labs.sarif
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: endorlabs-java-webapp-demo
          path: |
            target/endor-java-webapp-demo.jar
        
      
